verbose: 0
SAVE: 1

DT: 0.1
DURATION: 350.0

T_STEADY: 100.0
T_WINDOW: 10.0

T_STIM_ON: 200.0
T_STIM_OFF: 250.0
I0: [0.5, 0.0, 0.5]
PHI0: None
SIGMA_EXT: .25

FILE_NAME: chaos
TF_NAME: TL
TF_GAIN: 4

N_POP: 3
N: 30000
K: 1000
frac: [.6, .2, .2]

TAU_SYN: [4., 4., 2.]

IF_NMDA: 0
TAU_NMDA: [4., 4., 2.]

FF_DYN: 1
TAU_FF: [4., 4., 4.]

THRESH_DYN: 0
THRESH: [0.0, 0.0, 0.0]

RATE_DYN: 0
TAU_MEM: [20., 20., 10]

GAIN: 1.0
Jab: [0.44, 0.44, -0.28, 0.44, 0.44, -0.28, 0.67, 0.67, -0.34]
Iext: [0.35, 0.35, 0.25]
M0: 1

SEED: 10
STRUCTURE: ['spec', 'None', 'None', 'None', 'spec', 'None', 'None', 'None', 'None']
SIGMA: [10.0, 0., 0.0, 10.0, 0.0, 0.0, 10.0, 0.0, 0.0]

TOLERANCE: 1.e-9
MAXITER: 100
