DT: 0.1
DURATION: 1.0

N: 1000
K: 100

frac: [0.8, 0.2]

VL: [0., 0.]
V_TH: [1., 1.]

TAU_SYN: [3., 2., 3., 2.]
TAU_MEM: [10., 10.]

Jab: [1., 2., 3., 4.]
Iext: [1., 2.]
M0: 0.01

STRUCTURE: N
SIGMA: [0.25, 0.25]
