verbose: 0
SAVE: 1

DT: 0.1
DURATION: 1000.0

T_STEADY: 500.0
T_WINDOW: 10.0

T_STIM_ON: 750.0
T_STIM_OFF: 800.0
I0: [0.5, 0.0, 0.0]
PHI0: None
SIGMA_EXT: .25

FILE_NAME: chaos
TF_NAME: TL
TF_GAIN: 1

N_POP: 3
N: 30000
K: 1000
frac: [.333333333333333335, .333333333333333335, .333333333333333335]

SYN_DYN: 0
TAU_SYN: [4., 4., 2.]

IF_NMDA: 0
TAU_NMDA: [4., 4., 2.]

FF_DYN: 0
TAU_FF: [4., 4., 4.]

THRESH_DYN: 0
THRESH: [0.0, 0.0, 0.0]

RATE_DYN: 1
TAU_MEM: [6., 6., 2.]

GAIN: 1.0
Jab: [0.44, 0.44, -0.28, 0.44, 0.44, -0.28, 0.67, 0.67, -0.34]
# Jab: [1, 1, -1.5, 1, 1, -1.5, 1, 1, -1]
Iext: [0.5, 0.5, 0.25]
M0: 1.0

SEED: 10
STRUCTURE: ['spec', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None']
SIGMA: [6.5, 0., 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

IF_LEARNING: 0

TOLERANCE: 1.e-12
MAXITER: 100
