verbose: 0
SAVE: 1

DT: 0.1
DURATION: 500.0

T_STEADY: 100.0
T_WINDOW: 10.0

T_STIM_ON: 200.0
T_STIM_OFF: 250.0
I0: 0.1
PHI0: None

FILE_NAME: chaos
TF_NAME: TL

N_POP: 1
N: 20000
K: 1000
frac: [.5, .5]

TAU_SYN: [3., 2., 3., 2.]
THRESH: 50.0

RATE_DYN: 1
TAU_MEM: [10., 5.]

GAIN: 1.0
Jab: [0.44, -0.28, 0.67, -0.34]
Iext: [0.5, 0.25]
M0: 0.001

SEED: 10
STRUCTURE: spec
SIGMA: 5.0
