verbose: 0
SAVE: 1

DURATION: 2000.0

T_STEADY: 250.0
T_WINDOW: 10.0

T_STIM_ON: 500.0
T_STIM_OFF: 1000.0

DT: 0.1
# DURATION: 20.0

# T_STEADY: 0 # 4250.0
# T_WINDOW: 10.0

# T_STIM_ON: 4500.0
# T_STIM_OFF: 4750.0

I0: [0.2, 0.]
PHI0: 180
SIGMA0: 1.0

SIGMA_EXT: 10.0
PERT_TYPE: 'cos'

FILE_NAME: chaos2
TF_NAME: TL
TF_GAIN: 1

N_POP: 2
N: 10000
K: 700
frac: [.5, .5]

SYN_DYN: 1
TAU_SYN: [4., 2.]

IF_NMDA: 0
TAU_NMDA: [20., 20.]

FF_DYN: 0
TAU_FF: [4., 4.]
VAR_FF: [10., 4.]

THRESH_DYN: 0
THRESH: [0.00, 0.00]

RATE_DYN: 0
TAU_MEM: [5.0, 2.0]

GAIN: 1.0
Jab: [0.44, -0.28, 0.67, -0.34]
# Jab: [1, -1.5, 1, -1]
# Jab: [0.00133, -0.08, 0.02, -0.133]
# Jab: [0.00347, -0.10, 0.05, -0.15]

Iext: [0.5, 0.25]
# Iext: [1.9, 4.0]

M0: 1.0

IF_LEARNING: 0
IF_STP: 0

SEED: 10
STRUCTURE: ['spec_cos', 'None', 'None', 'None']
SIGMA: [0.0, 2.5, 0.5, 2.5]
KAPPA: [2.0, 0.5, 3.5, 0.5]
PHASE: 0 

TOLERANCE: 1.e-12
MAXITER: 100
