verbose: 1
SAVE: 1

DT: 0.1
DURATION: 1000.0

T_STEADY: 10.0
T_WINDOW: 10.0

FILE_NAME: chaos
TF_NAME: TL

N_POP: 1
N: 20000
K: 1000

frac: [.5, .5]

VL: [0., 0.]
V_TH: [1., 1.]

TAU_SYN: [3., 2., 3., 2.]
TAU_MEM: [20., 10.]

GAIN: 1.0
Jab: [0.44, -0.28, 0.67, -0.34]
Iext: [0.5, 0.25]
M0: 0.001

SEED: 10
STRUCTURE: spec
SIGMA: 8
