verbose: 0
SAVE: 1

DT: 0.1
DURATION: 1500.0

T_STEADY: 100.0
T_WINDOW: 10.0

T_STIM_ON: 500.0
T_STIM_OFF: 1000.0
I0: [5.0, 0.]
PHI0: None
SIGMA0: 180

SIGMA_EXT: 2.0
PERT_TYPE: 'cos'

FILE_NAME: chaos
TF_NAME: TL
TF_GAIN: 1

N_POP: 2
N: 1440
K: 1.0
frac: [.5, .5]

SYN_DYN: 0
TAU_SYN: [4., 2.]

IF_NMDA: 0
TAU_NMDA: [20., 20.]

FF_DYN: 2
TAU_FF: [4., 4.]
VAR_FF: [4., 4.]

THRESH_DYN: 0
THRESH: [0.00, 0.00]

RATE_DYN: 1
TAU_MEM: [10., 5.]

GAIN: 1.0
Jab: [0.5, -1.0, 5.0, 0]
Iext: [40., 1.0]
M0: 1.0

IF_LEARNING: 0
IF_STP: 0

SEED: 10
STRUCTURE: ['all_cos', 'all_cos', 'all', 'all_cos']
SIGMA: [0.0, 0.0, 0.0, 0.0]
KAPPA: [1.0, 0.0, 1.0, 0.0]
PHASE: 180.

TOLERANCE: 1.e-12
MAXITER: 100
