verbose: 0
SAVE: 1

DT: 0.1
DURATION: 500.0

T_STEADY: 100.0
T_WINDOW: 10.0

T_STIM_ON: 200.0
T_STIM_OFF: 250.0
I0: [0.25, 0.25]
PHI0: None

FILE_NAME: chaos
TF_NAME: TL
TF_GAIN: 4

N_POP: 2
N: 5000
K: 500
frac: [.75, .25]

TAU_SYN: [4., 2.]

IF_NMDA: 0
TAU_NMDA: [20., 20.]

FF_DYN: 0
TAU_FF: [4., 4.]

THRESH_DYN: 0
THRESH: [0.0, 0.0]

RATE_DYN: 0
TAU_MEM: [15., 10.]

GAIN: 1.0
Jab: [0.44, -0.28, 0.67, -0.34]
# Jab: [1, -1.5, 1, -1]

Iext: [0.5, 0.25]
M0: 0.001

IF_LEARNING: 1

SEED: 10
STRUCTURE: ['spec', 'None', 'None', 'None']
SIGMA: [4.0, 0.0, 0.0, 0.0]
