verbose: 1
SAVE: 1

DT: 0.001
DURATION: 5.0

T_STEADY: 1.0
T_WINDOW: .05

T_STIM_ON: 2.0
T_STIM_OFF: 2.5

I0: [1.0, 0.]
I1: [0.05, 0.0]

PHI0: 180.0
SIGMA0: 1.0
DPHI: 0.25

SIGMA_EXT: 1.0
PERT_TYPE: 'cos'

TF_NAME: TL
TF_GAIN: 1.0

N_POP: 1
N: 1000
K: 1.0
frac: [1.0]

SYN_DYN: 0
TAU_SYN: [2.]

IF_NMDA: 0
TAU_NMDA: [20.]

FF_DYN: 2
TAU_FF: [4.]
VAR_FF: [30.0]

THRESH_DYN: 0
THRESH: [15.0]
TAU_THRESH: [0.08]

RATE_DYN: 1
TAU_MEM: [.020]
RATE_NOISE: 0
RATE_VAR: 0.0

GAIN: 1.0

FILE_NAME: bump
           
Jab: [-2.75]
Iext: [14.0]
M0: 1.0

IF_LEARNING: 0
IF_STP: 0

##############
# Connectivity
##############
IF_LOAD_MAT: 0
IF_SAVE_MAT: 1

SEED: 1
STRUCTURE: ['all_cos']
SIGMA: [0.0]
KAPPA: [0.4]
PHASE: 180.0

TOLERANCE: 1.e-12
MAXITER: 100

