verbose: 0
SAVE: 1

DT: 0.1
DURATION: 2500.0

T_STEADY: 500.0
T_WINDOW: 10.0

T_STIM_ON: 1000.0
T_STIM_OFF: 2000.0
I0: [50.0, 0.]
PHI0: 180.0
SIGMA0: 1.0

SIGMA_EXT: 1.0
PERT_TYPE: 'cos'

FILE_NAME: bump
TF_NAME: TL
TF_GAIN: 1

N_POP: 1
N: 1000
K: 1.0
frac: [1.0]

SYN_DYN: 0
TAU_SYN: [2.]

IF_NMDA: 0
TAU_NMDA: [20.]

FF_DYN: 2
TAU_FF: [4.]
VAR_FF: [100.0]

THRESH_DYN: 0
THRESH: [0.00]
TAU_THRESH: [100., 100.]

RATE_DYN: 1
TAU_MEM: [10.0]

GAIN: 1.0
Jab: [-300.0]
Iext: [25.0]
M0: 1.0

IF_LEARNING: 0
IF_STP: 1

SEED: None
STRUCTURE: ['all_cos']
SIGMA: [0.0]
KAPPA: [.40]
PHASE: 180.0

TOLERANCE: 1.e-12
MAXITER: 100
