verbose: 0
SAVE: 1

DT: 0.1
DURATION: 1500.0

T_STEADY: 250.0
T_WINDOW: 10.0

T_STIM_ON: 500.0
T_STIM_OFF: 1000.0
I0: [2.0, 0.0]
PHI0: None
SIGMA_EXT: 3.0

FILE_NAME: chaos2
TF_NAME: NL
TF_GAIN: 1

N_POP: 2
N: 1000
K: 1
frac: [.5, .5]

SYN_DYN: 0
TAU_SYN: [4., 2.]

IF_NMDA: 0
TAU_NMDA: [20., 20.]

FF_DYN: 2
# 0, 1 or 2 for noisy ff inputs
TAU_FF: [4., 4.]
VAR_FF: [4., 4.]

THRESH_DYN: 0
THRESH: [0.00, 0.00]

RATE_DYN: 1
TAU_MEM: [4., 2.]

GAIN: 1.0
Jab: [0.068, -0.042, 0.13, -0.13]
# Jab: [1.0, -0.75, 1.0, -1.0]
Iext: [0., 0.5]
M0: 1.0

IF_LEARNING: 0

SEED: 10
STRUCTURE: ['all', 'all', 'all', 'all']
SIGMA: [2.5, 0.0, 2.5, 0.0]
# SIGMA: [.75, 0.0, .75, 0.0]

TOLERANCE: 1.e-12
MAXITER: 100