verbose: 0
SAVE: 1

DURATION: 2500.0

T_STEADY: 750.0
T_WINDOW: 10.0

T_STIM_ON: 1000.0
T_STIM_OFF: 1500.0

DT: 0.1
# DURATION: 20.0

# T_STEADY: 0 # 4250.0
# T_WINDOW: 10.0

# T_STIM_ON: 4500.0
# T_STIM_OFF: 4750.0

I0: [5.0, 0.]
PHI0: 180
SIGMA0: 1.0

SIGMA_EXT: 10.0
PERT_TYPE: 'cos'

FILE_NAME: chaos
TF_NAME: TL
TF_GAIN: 1

N_POP: 2
N: 2000
K: 100
frac: [.5, .5]

SYN_DYN: 1
TAU_SYN: [4., 2.]

IF_NMDA: 0
TAU_NMDA: [20., 20.]

FF_DYN: 0
TAU_FF: [4., 4.]
VAR_FF: [10., 4.]

THRESH_DYN: 0
THRESH: [1.00, 1.00]
TAU_THRESH: [100., 100.]

RATE_DYN: 0
TAU_MEM: [20.0, 10.0]

GAIN: 1.0
Jab: [100.5, -1.4, 1.2, -.9]
# Jab: [70.0, -0.28, 0.67, -0.34]
# Jab: [1, -1.5, 1, -1]
# Jab: [0.00133, -0.08, 0.02, -0.133]
# Jab: [0.00347, -0.10, 0.05, -0.15]

# Iext: [0.5, 0.25]
Iext: [2.0, 1.185]
J# Iext: [1.9, 4.0]

M0: 1.0

IF_LEARNING: 0
IF_STP: 1

SEED: None
STRUCTURE: ['spec_cos', 'None', 'None', 'None']
SIGMA: [1.0, 0.0, 0.0, 0.0]
KAPPA: [4.0, 0.0, 0.0, 0.0]
PHASE: 0 

TOLERANCE: 1.e-12
MAXITER: 100
